FROM itdoginfo/openwrt-sdk-apk:25.12.3

ARG PODKOP_VERSION
ENV PODKOP_VERSION=${PODKOP_VERSION}

COPY ./podkop /builder/package/feeds/utilities/podkop
COPY ./luci-app-podkop-plus /builder/package/feeds/luci/luci-app-podkop-plus

RUN ./scripts/feeds update -a && \
    ./scripts/feeds install -a && \
    make defconfig && \
    make package/luci-app-podkop-plus/compile -j4 V=s
